services:
  - type: worker
    name: mqtt-firebase-worker
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        fromSecret: mqtt-firebase-service-credentials
